### PR TITLE
Feature/ruby 3.1.3

### PR DESCRIPTION
**Pull request by taraszka**

### CODE REVIEW

**Comment by taraszka** [comment]
```
❯ ./rubyc -V
3.1.3
❯ ./rubyc --version
3.1.3.dev
```

It is working just fine. It also compiles the `.rb` files to binary. 

Ruby 3.1.3 is compatible with macOS Ventura (it compile ruby under Xcode 14)

**Comment by ericbeland** [comment]
Hey, this is great! I'll take a look. Not sure how I missed the email notification.

**Comment by ericbeland** [comment]
I tried this out and it seemed to work very well. Thanks for sharing this--super awesome!

🥇

**Comment by ericbeland** [comment]
@taraszka, have you tried compiling on an M1 mac, by chance?  When I do, if I run:

`otool -L /Users/ebeland/apps/ruby-packer/rubyc`

I get the output below, which has a libssl/libcrypto dependency. I'd like to get, both for myself, and to link in the readme, a clean compilation of rubyc on Arm64 without those two extra dependencies. On my intel mac, these dependencies don't show up, but I'm not sure why--it seems like they are being statically linked, which is desirable. I'm wondering how this looks for you, and if you could make a clean binary?

/Users/ebeland/apps/ruby-packer/rubyc:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/var/folders/s9/mtk8pgj529j4lq_b7bl2fkkc0000gn/T/rubyc/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/var/folders/s9/mtk8pgj529j4lq_b7bl2fkkc0000gn/T/rubyc/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by taraszka** [comment]
Oh crap, I will have a look.

**Comment by taraszka** [comment]
Oh, I have the same on my ARM Mac:
```
❯ otool -L ~/bin/rubyc
/Users/ktaraszk/bin/rubyc:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1953.255.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/var/folders/dj/mj61btns60l99ksx8cln34ym0000gn/T/rubyc/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/var/folders/dj/mj61btns60l99ksx8cln34ym0000gn/T/rubyc/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
```

I will try to fix it.

**Comment by taraszka** [comment]
Yeah, I had the same issue with Intel too. I think I know where the problem is or might be.

**Comment by ericbeland** [comment]
I also have a report of:

-------------------------------
rubyc: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=470a81d8826ed98cb6cad5d370559b2040a5fcd1, for GNU/Linux 3.2.0, with debug_info, not stripped

seems that debugging symbols are included in the final package regardless of if I asked for them or not.
--------------------------------

I'm not sure if that's new or not, though.

**Comment by ericbeland** [comment]
@taraszka Did you have a chance to look at why it is linking to those temp files on ARM? It sounded like you might know where that would be? If you can give me pointers, I can _try_?  I'm not well versed in C compilation though.  I'd like to get some built binaries up. Thoughts?

**Comment by taraszka** [comment]
No, I am currently busy with another task at work, but I will get back to it maybe next week.

**Comment by ericbeland** [comment]
Hi @taraszka. Would you have a few minutes to give me some pointers to where the issue might be happening, so I can take a look?

**Pull request merged**
